# Generated by Django 6.0.7 on 2026-07-23 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Kitap Adı')),
                ('yazar', models.CharField(max_length=100, verbose_name='Yazar')),
                ('ozet', models.TextField(verbose_name='Kitap Özeti')),
                ('kapak_resmi', models.ImageField(blank=True, null=True, upload_to='kapaklar/', verbose_name='Kitap Kapağı')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(verbose_name='Yorum / Tartışma')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='kitaplar.kitap', verbose_name='Kitap')),
                ('yazan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
