# Generated by Django 6.0.7 on 2026-07-24 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='ayin_kitabi',
            field=models.BooleanField(default=False, verbose_name='Ayın Kitabı mı?'),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='kapak_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='kitap_kapaklari/'),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='ozet',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='yazar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='icerik',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='kitap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='kitaplar.kitap'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='yazan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
