# Generated by Django 6.0.7 on 2026-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0002_kitap_ayin_kitabi_alter_kitap_baslik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='puan',
            field=models.IntegerField(choices=[(5, '5 - Mükemmel'), (4, '4 - Çok İyi'), (3, '3 - Ortalama'), (2, '2 - Kötü'), (1, '1 - Çok Kötü')], default=5),
        ),
    ]
