# Generated by Django 6.0.7 on 2026-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0006_yorum_begeniler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='kapak_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='kitap_kapaklari/', verbose_name='Kapak Resmi'),
        ),
    ]
