# Generated by Django 6.0.7 on 2026-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0007_alter_kitap_kapak_resmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='ai_gorsel_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='AI Görsel Adresi'),
        ),
    ]
