# Generated by Django 6.0.7 on 2026-07-24 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0003_yorum_puan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OkumaListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('okunacak', 'Okuyacaklarım'), ('okundu', 'Okuduklarım')], max_length=20)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitaplar.kitap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kitap')},
            },
        ),
    ]
