# Generated by Django 6.0.7 on 2026-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0004_okumalistesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='kategori',
            field=models.CharField(choices=[('roman', 'Roman'), ('bilim-kurgu', 'Bilim Kurgu'), ('klasik', 'Dünya Klasikleri'), ('felsefe', 'Felsefe & Psikoloji'), ('tarih', 'Tarih & Biyografi'), ('kisisel-gelisim', 'Kişisel Gelişim'), ('diger', 'Diğer')], default='roman', max_length=50, verbose_name='Kategori'),
        ),
    ]
