# Generated by Django 6.0.7 on 2026-07-24 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0005_kitap_kategori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='begeniler',
            field=models.ManyToManyField(blank=True, related_name='begenilen_yorumlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
